# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAINED_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features  
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

metrics:
  SCORES: scores.json

plots:
  PRC: prc.json
  ROC: roc.json

source_data:
  URL: https://raw.githubusercontent.com/c17hawke/common-data-repo/main/data.xml
  data_dir: data
  data_file: data.xml

